=== ronakbakshi/Fall-2015-Web-Apps-and-Servlets/XMLDTDJavaApplication/songs.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document: songs.dtd
    Description: Song information.
    Song lengths are in minutes (should it be an integer number  NOT a floating point).
    Song ratings are integers between 0 and 10 (inclusive).
-->
<!ELEMENT songList (song+)>
<!ELEMENT song (title, singer, length, ratingList)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT singer (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT ratingList (rating+)>
<!ELEMENT rating (#PCDATA)>

=== ronakbakshi/Fall-2015-Web-Apps-and-Servlets/XMLDTDJavaApplication/songs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE songList SYSTEM 'songs.dtd'>
<songList>
<song>
   <title>Uptown Funk</title>
   <singer>Mark Ronson</singer>
   <length>7</length>
   <ratingList>
      <rating>8</rating>
      <rating>5</rating>
   </ratingList>
</song>
    <song>
   <title>Wildest Dreams</title>
   <singer>Taylor Swift</singer>
   <length>6</length>
   <ratingList>
      <rating>9</rating>
      <rating>10</rating>
	  <rating>10</rating>
   </ratingList>
</song>
<song>
   <title>American Oxygen</title>
   <singer>Rihanna</singer>
   <length>4</length>
   <ratingList>
      <rating>7</rating>
	  <rating>10</rating>
      <rating>4</rating>
   </ratingList>
</song>
<song>
   <title>Animals</title>
   <singer>Maroon5</singer>
   <length>5</length>
   <ratingList>
      <rating>6</rating>
      <rating>10</rating>
	  <rating>9</rating>
   </ratingList>
</song>

</songList>
